server:
  port: ${PORT}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

resilience4j:
  ratelimiter:
    instances:
      login:
        limit-for-period: 5
        limit-refresh-period: 60s
        timeout-duration: 0
  circuitbreaker:
    instances:
      login:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        sliding-window-size: 5

cors:
  allowed-origins:
    - http://localhost:3000

jwt:
  # Use a BASE64-encoded secret of at least 256 bits (>= 32 bytes after decode)
  # Replace this with your own! Example shown only for local/dev.
  secret: "bXktdmVyeS1sb25nLWFuZC1zYWZlLXN1cGVyLXNlY3JldC1rZXktdGhhdC1pcy1iYXNlNjQ="
  expiration-ms: 3600000   # 1 hour = 3600000 ms
